# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'CharlApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CharlApp
  pod 'Firebase/Analytics'
  pod 'SVProgressHUD'
  pod 'ChameleonFramework'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
   # Optionally, include the Swift extensions if you're using Swift.

end
